name: Rust 测试

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: [ubuntu-latest,windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: 设置 Rust
      uses: dtolnay/rust-toolchain@stable
    - name: 运行测试
      run:
        cargo run
